// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"reflect"
	"sync"

	"github.com/phogolabs/reflectify"
)

type Provider struct {
	NewStub        func(reflect.Value) reflectify.Provider
	newMutex       sync.RWMutex
	newArgsForCall []struct {
		arg1 reflect.Value
	}
	newReturns struct {
		result1 reflectify.Provider
	}
	newReturnsOnCall map[int]struct {
		result1 reflectify.Provider
	}
	ValueStub        func(*reflectify.Context) (interface{}, error)
	valueMutex       sync.RWMutex
	valueArgsForCall []struct {
		arg1 *reflectify.Context
	}
	valueReturns struct {
		result1 interface{}
		result2 error
	}
	valueReturnsOnCall map[int]struct {
		result1 interface{}
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Provider) New(arg1 reflect.Value) reflectify.Provider {
	fake.newMutex.Lock()
	ret, specificReturn := fake.newReturnsOnCall[len(fake.newArgsForCall)]
	fake.newArgsForCall = append(fake.newArgsForCall, struct {
		arg1 reflect.Value
	}{arg1})
	fake.recordInvocation("New", []interface{}{arg1})
	fake.newMutex.Unlock()
	if fake.NewStub != nil {
		return fake.NewStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.newReturns
	return fakeReturns.result1
}

func (fake *Provider) NewCallCount() int {
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return len(fake.newArgsForCall)
}

func (fake *Provider) NewCalls(stub func(reflect.Value) reflectify.Provider) {
	fake.newMutex.Lock()
	defer fake.newMutex.Unlock()
	fake.NewStub = stub
}

func (fake *Provider) NewArgsForCall(i int) reflect.Value {
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	argsForCall := fake.newArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Provider) NewReturns(result1 reflectify.Provider) {
	fake.newMutex.Lock()
	defer fake.newMutex.Unlock()
	fake.NewStub = nil
	fake.newReturns = struct {
		result1 reflectify.Provider
	}{result1}
}

func (fake *Provider) NewReturnsOnCall(i int, result1 reflectify.Provider) {
	fake.newMutex.Lock()
	defer fake.newMutex.Unlock()
	fake.NewStub = nil
	if fake.newReturnsOnCall == nil {
		fake.newReturnsOnCall = make(map[int]struct {
			result1 reflectify.Provider
		})
	}
	fake.newReturnsOnCall[i] = struct {
		result1 reflectify.Provider
	}{result1}
}

func (fake *Provider) Value(arg1 *reflectify.Context) (interface{}, error) {
	fake.valueMutex.Lock()
	ret, specificReturn := fake.valueReturnsOnCall[len(fake.valueArgsForCall)]
	fake.valueArgsForCall = append(fake.valueArgsForCall, struct {
		arg1 *reflectify.Context
	}{arg1})
	fake.recordInvocation("Value", []interface{}{arg1})
	fake.valueMutex.Unlock()
	if fake.ValueStub != nil {
		return fake.ValueStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.valueReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Provider) ValueCallCount() int {
	fake.valueMutex.RLock()
	defer fake.valueMutex.RUnlock()
	return len(fake.valueArgsForCall)
}

func (fake *Provider) ValueCalls(stub func(*reflectify.Context) (interface{}, error)) {
	fake.valueMutex.Lock()
	defer fake.valueMutex.Unlock()
	fake.ValueStub = stub
}

func (fake *Provider) ValueArgsForCall(i int) *reflectify.Context {
	fake.valueMutex.RLock()
	defer fake.valueMutex.RUnlock()
	argsForCall := fake.valueArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Provider) ValueReturns(result1 interface{}, result2 error) {
	fake.valueMutex.Lock()
	defer fake.valueMutex.Unlock()
	fake.ValueStub = nil
	fake.valueReturns = struct {
		result1 interface{}
		result2 error
	}{result1, result2}
}

func (fake *Provider) ValueReturnsOnCall(i int, result1 interface{}, result2 error) {
	fake.valueMutex.Lock()
	defer fake.valueMutex.Unlock()
	fake.ValueStub = nil
	if fake.valueReturnsOnCall == nil {
		fake.valueReturnsOnCall = make(map[int]struct {
			result1 interface{}
			result2 error
		})
	}
	fake.valueReturnsOnCall[i] = struct {
		result1 interface{}
		result2 error
	}{result1, result2}
}

func (fake *Provider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	fake.valueMutex.RLock()
	defer fake.valueMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Provider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ reflectify.Provider = new(Provider)
